### ISSUE TITLE
Web vim mode related files menu UX bug

### ISSUE THREAD

**Issue by bolDeju** [alonswartz/notesium#78]
Mentioned [here](https://github.com/alonswartz/notesium/issues/72#issuecomment-2444267843).

Vim mode shortcut `<space> n k` incorrect behavior.
- Firefox 131 and 130 related.
- Works on chrome correctly.
- InsertLink is triggered and even focused.
- Loses focus after a small time (~1 sec).
- If you try to type, typing is done with opened dialog. User input is in note, from where menu was triggered.
- `Esc` is not working (to close triggered menu).

**Comment by alonswartz** [comment]
Thanks for the report.

This issue affects all `<space> n char` global keybindings when triggered from a note with Vim mode enabled. I've identified the offending code, and will work on a fix.

**Comment by alonswartz** [comment]
@bolDeju - this should fix the issue (as usual, the github action build artifact is available for testing).

From a UX perspective, the active note should regain focus if only `space` is pressed, or when the Finder (triggered by `space n char`) is cancelled.

**Comment by alonswartz** [comment]
this should handle the expected UX: 
- [commit](https://github.com/alonswartz/notesium/pull/79/commits/ba7d34e0863fb59566d19245866fc4dfe51c82e5)
- [gh build](https://github.com/alonswartz/notesium/actions/runs/11594369266)

**Comment by bolDeju** [comment]
1. not fixed 
https://github.com/user-attachments/assets/e1eff687-711c-435f-94b5-fcd795fe1145
2. is it just me or ?
![image](https://github.com/user-attachments/assets/a696a5aa-f487-46bd-948c-1bc1dc548b7b)

**Comment by alonswartz** [comment]
Sorry about that, I think I got it this time: 
- https://github.com/alonswartz/notesium/pull/79/commits/0ee8a480eb9e6d49c98530234b272103d21896ab
- https://github.com/alonswartz/notesium/actions/runs/11610464442

Regarding `NOTESIUM_DIR`, environment variables are scoped in the shell, meaning they’re only accessible to commands that run in a new process if explicitly exported or set inline with the command.

```bash
$ export NOTESIUM_DIR="path/to/dir"
$ notesium home
# OR
$ NOTESIUM_DIR="path/to/dir" notesium home
```

BTW - you can toggle vim/default mode in the status bar:
![image](https://github.com/user-attachments/assets/f9ac4b91-6fbc-4385-bef1-848e8a02f1f1)

**Comment by alonswartz** [comment]
This is now part of the [Notesium v0.6.1 release](https://github.com/alonswartz/notesium/releases/tag/v0.6.1). Thanks for your help and patience!
